
ARROW_UP       = "\uf55c"
ARROW_DOWN     = "\uf544"

DIRECTORY_ICON = "\ue5ff"
FILE_ICON      = "\uf713"
IMAGE_FILE     = "\uf71e"
VECTOR_FILE    = "\ufa60"#"\ufa53"#"\ufa5d"
MUSIC_FILE     = "\uf886"
VIDEO_FILE     = "\uf03d"
ADVANCED_TEXT  = "\uf718"
MAKEFILE       = "\uf68c"
CONFIG         = "\uf423"

C_FILE         = "\ue61e"
CPLUSPLUS_FILE = "\ue61d"
HASKELL_FILE   = "\ue777"
HTML_FILE      = "\uf72d"
JSON_FILE      = "\ue60b"
JAVA_FILE      = "\ue738"
JS_FILE        = "\uf81d"
PYTHON_FILE    = "\ue235"
REACT_FILE     = "\ue625"
RUBY_FILE      = "\ue23e"
SCRIPT_FILE    = "\ue795"
